.TH dp_deserialize_messages_from_file 3dp "July 14, 2025" "Disaster Party" "Disaster Party Manual"

.SH NAME
dp_deserialize_messages_from_file \- deserializes a file into an array of dp_message_t structures

.SH SYNOPSIS
.B #include <disasterparty.h>
.sp
.BI "int dp_deserialize_messages_from_file(const char* " "path" ", dp_message_t** " "messages_out" ", size_t* " "num_messages_out" ");"

.SH DESCRIPTION
.B dp_deserialize_messages_from_file()
reads a JSON formatted string from the file specified by
.I path
and deserializes it into an array of
.BR dp_message_t
structures. The caller is responsible for freeing the output array
.I messages_out
and its contents by calling
.BR dp_free_messages(3dp).

.SH RETURN VALUE
Returns 0 on success and a negative value on failure.

.SH SEE ALSO
.BR dp_serialize (3dp),
.BR dp_serialize_messages_to_file (3dp),
.BR dp_free_messages (3dp)

.SH BUGS
No known bugs.

.SH AUTHOR
Kirn Gill II <segin2005@gmail.com>