.TH dp_deserialize_messages_from_json_str 3dp "July 14, 2025" "Disaster Party" "Disaster Party Manual"

.SH NAME
dp_deserialize_messages_from_json_str \- deserializes a JSON formatted string into an array of dp_message_t structures

.SH SYNOPSIS
.B #include <disasterparty.h>
.sp
.BI "int dp_deserialize_messages_from_json_str(const char* " "json_str" ", dp_message_t** " "messages_out" ", size_t* " "num_messages_out" ");"

.SH DESCRIPTION
.B dp_deserialize_messages_from_json_str()
parses a JSON formatted string and deserializes it into an array of
.BR dp_message_t
structures. The caller is responsible for freeing the output array
.I messages_out
and its contents by calling
.BR dp_free_messages(3dp).

.SH RETURN VALUE
Returns 0 on success and a negative value on failure.

.SH SEE ALSO
.BR dp_serialize (3dp),
.BR dp_serialize_messages_to_json_str (3dp),
.BR dp_free_messages (3dp)

.SH BUGS
No known bugs.

.SH AUTHOR
Kirn Gill II <segin2005@gmail.com>